### ISSUE TITLE
Hey guys.. how do I use this? :)

### ISSUE THREAD

**Issue by jtsternberg** [projectkudu/PHPManager#4]
README says "PHP Manager is an Azure Websites Site Extension that allows users to manage their PHP settings." but gives no indication os where that management happens.

**Comment by davidebbo** [comment]
See http://azure.microsoft.com/blog/2014/06/20/azure-web-sites-extensions/ for an intro on how to install site extensions into an Azure Website. PHPManager is one of the extensions on the gallery ([here](http://www.siteextensions.net/packages/phpmanager/)).

**Comment by jtsternberg** [comment]
@davidebbo I understand how to install the extension, and what the gallery is. My question is that I have added the extension, but I'm not sure what benefits/functionality it (PHPManager) is supposed to give me?

**Comment by davidebbo** [comment]
Ok, so to make sure I understand, you are successfully able to run the extension, but you need more details about what it does?

**Comment by jtsternberg** [comment]
If by 'run the extension', you mean install it via the azure portal (http://b.ustin.co/1eGS8), then yes, we have that part down.

**Comment by davidebbo** [comment]
No, I mean install it, and then actually run it. :) i.e. click the browse button for that extension.

**Comment by jtsternberg** [comment]
Aaaaah.. there it is.. the 'browse' button. I got it now. Thanks your explanation/detail.

**Comment by davidebbo** [comment]
That might be a sign that our UI is not very discoverable :(

**Comment by jtsternberg** [comment]
I think simply describing (in the readme and adding to the description: http://b.ustin.co/1hlip ) how to get to that browse button in the portal would be helpful.

**Comment by davidebbo** [comment]
I updated the readme.

**Comment by jtsternberg** [comment]
:+1:
